<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Brand;
use App\Handlers\ImageHandler;
use App\Handlers\PizzaSeedHandler;

class BellatoriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $brand = Brand::updateOrCreate([
            'slug' => 'bellatoria',
        ], [
            'name' => 'Bellatoria',
            'website' => 'https://www.shopbernatellospizza.com/',
            'brand_story' => "Bellatoria is one of the premium frozen pizza brands developed by Bernatello’s Pizza, Inc. The company—originally established as Bernie’s Pizza in the early 1980s—expanded its product lineup over the years through acquisitions and brand diversification. As part of this strategy, Bernatello’s introduced Bellatoria to offer upscale, Italian‐inspired pizzas with ultra–thin crusts and gourmet toppings. The name “Bellatoria” was chosen for its distinctly Italian sound. While it doesn’t have a strict translation, some suggest it echoes the phrase “bella tori” (roughly “beautiful bull”), capturing an evocative, classic Italian vibe that fits the brand’s identity. Today, Bellatoria is marketed as a lifestyle experience as much as a food product—inviting customers to enjoy the “taste of Italy” at home in a convenient frozen format. It sits alongside other Bernatello’s brands like Orv’s, Brew Pub, and Roma, each targeting different segments of the frozen pizza market.",
            'founded_year' => '1980', // Approximately based on "28 years in" from website content
            'description' => "Bellatoria is a lifestyle, a relaxed mood, a fond memory, an all-encompassing experience of how life and food mingle with each other. Scroll down to find our Italian inspired pizzas.  There is always something cooking in our Kitchen! Please enjoy the Bellatoria experience! “Where the Taste of Italy comes to your Table!®",
        ]);

        $pizzas = [
            [
                'name' => "Ultra Thin Crust Ultimate Supreme",
                'slug' => "ultra-thin-crust-ultimate-supreme",
                'tags' => ['thin-crust', 'supreme', 'sausage', 'parmesan', 'asiago', 'pepperoni', 'peppers', 'onion', 'olives'],
                'description' => "Ultra Thin and Crispy Pizza topped with Mozzarella, Parmesan, Asiago cheese, rich Italian style sauce, Italian sausage, pepperoni, roasted red and green peppers, red onions & black olives.",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/152/713/9998_Bel_UTC_UltSup_LR__26892.1588002789.jpg?c=2",
                'ingredients' => "Low Moisture Part-Skim Mozzarella Cheese (Pasteurized Part-Skim Milk, Salt, Cheese Cultures, Enzymes), Sauce (Water, Tomato Paste, Seasoning (Modified Food Starch, Sugar, Salt, Spices, Maltodextrin, Dextrose, Garlic and Onion, Guar Gum, Citric Acid, Beet Powder, Extractives of Paprika [Color]), Corn oil), Crust (Enriched Flour (Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid), Water, Soybean Oil, Dough Conditioner (Malted Barley Flour, Dextrose), Yeast (Yeast, Sorbitan Monostearate, Ascorbic Acid), Dextrose, Extra Virgin Olive Oil, Salt), Cooked Italian Sausage (Pork, Spices, Salt, Dextrose, Garlic Powder, Paprika, Flavoring), Fire Roasted Vegetables Blend (Red Bell Pepper, Green Bell Pepper, Red Onion), Pepperoni (Pork, Beef, Salt, Spices, Contains 2% or less of Dextrose, Lactic Acid Starter Culture, Flavorings, Garlic Powder, Sodium Nitrite, BHA, BHT, Citric Acid, Oleoresin of Paprika, and/or Paprika, May Also Contain Water, Smoke Flavoring, Sodium Ascorbate), Black Olives (Black Olives, Salt, Ferrous Gluconate), Shredded Asiago Cheese (Asiago Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes), Powdered Cellulose (to Prevent Caking)), Grated Parmesan Cheese (Pasteurized Part-Skim Milk, Cheese Cultures, Salt, Enzymes, Starch, Powdered Cellulose [to Prevent Caking]), Seasoning (Spices (Oregano, Pepper, Basil), Maltodextrin, Onion & Garlic, Soybean Oil, Parsley). ",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '4 servings per container',
                    'serving_size' => '1/4 pizza (154g)',
                    'calories' => 350,
                    'total_fat' => '20g',
                    'saturated_fat' => '8g',
                    'trans_fat' => '0g',
                    'cholesterol' => '55mg',
                    'sodium' => '740mg',
                    'total_carbohydrate' => '24g',
                    'dietary_fiber' => '2g',
                    'total_sugars' => '4g',
                    'added_sugars' => '0g',
                    'protein' => '16g',
                    'vitamin_d' => '0.4mcg',
                    'calcium' => '340mg',
                    'iron' => '1.6mg',
                    'potassium' => '390mg',
                ]
            ],
            [
                'name' => "Ultra Thin Crust Ultimate Combo",
                'slug' => "ultra-thin-crust-ultimate-combo",
                'tags' => ['thin-crust', 'parmesan', 'asiago', 'sausage', 'pepperoni',],
                'description' => "Ultra Thin and Crispy Pizza topped with Mozzarella, Parmesan, Asiago cheese, rich Italian style sauce, sausage, pepperoni slices, and Italian spices.",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/151/714/9998_Bel_UTC_UltCombo_LR__93966.1588002853.jpg?c=2",
                'ingredients' => "Low Moisture Part-Skim Mozzarella Cheese (Pasteurized Part-Skim Milk, Salt, Cheese Cultures, Enzymes),  Crust (Enriched Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Soybean Oil, Dough Conditioner [Malted Barley Flour, Dextrose], Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid], Dextrose, Extra Virgin Olive Oil, Salt), Sauce (Water, Tomato Paste, Seasoning [Modified Food Starch, Sugar, Salt, Spices, Maltodextrin, Dextrose, Garlic and Onion, Guar Gum, Citric Acid, Beet Powder, Extractives of Paprika {Color}], Corn Oil), Cooked Sausage (Pork, Water, Spices, Salt, Dextrose, Garlic Powder, Paprika, Flavor), Pepperoni (Pork, Beef, Salt, Spices, Contains 2% or less of Dextrose, Lactic Acid Starter Culture, Flavorings, Garlic Powder, Sodium Nitrite, BHA, BHT, Citric Acid, Oleoresin of Paprika, and/or Paprika, May Also Contain Water, Smoke Flavoring, Sodium Ascorbate), Grated Parmesan Cheese (Pasteurized Part-Skim Milk, Cheese Cultures, Salt, Enzymes, Starch, Powdered Cellulose [to Prevent Caking]), Shredded Asiago Cheese (Asiago Cheese [Pasteurized Milk, Cheese Cultures, Salt, Enzymes] Powdered Cellulose [to Prevent Caking]), Seasoning (Spices (Oregano, Pepper, Basil), Maltodextrin, Onion & Garlic, Soybean Oil, Parsley).  ",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '4 servings per container',
                    'serving_size' => '1/4 pizza (138g)',
                    'calories' => 360,
                    'total_fat' => '21g',
                    'saturated_fat' => '9g',
                    'trans_fat' => '0g',
                    'cholesterol' => '55mg',
                    'sodium' => '750mg',
                    'total_carbohydrate' => '22g',
                    'dietary_fiber' => '2g',
                    'total_sugars' => '4g',
                    'added_sugars' => '0g',
                    'protein' => '16g',
                    'vitamin_d' => '0.5mcg',
                    'calcium' => '330mg',
                    'iron' => '1.6mg',
                    'potassium' => '370mg',
                ]
            ],
            [
                'name' => "Ultra Thin Crust Ultimate Pepperoni",
                'slug' => "ultra-thin-crust-ultimate-pepperoni",
                'tags' => ['thin-crust', 'pepperoni', 'parmesan', 'asiago',],
                'description' => "Ultra Thin and Crispy pizza topped with mozzarella, Parmesan, Asiago cheeses, rich Italian style sauce and pepperoni slices. ",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/149/716/9998_Bel_UTC_UltPep_LR__13900.1588002976.jpg?c=2",
                'ingredients' => "Low Moisture Part-Skim Mozzarella Cheese (Pasteurized Part-Skim Milk, Salt, Cheese Cultures, Enzymes), Crust (Enriched Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Soybean Oil, Dough Conditioner [Malted Barley Flour, Dextrose], Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid], Dextrose, Extra Virgin Olive Oil, Salt), Sauce (Water, Tomato Paste, Seasoning [Modified Food Starch, Sugar, Salt, Spices, Maltodextrin, Dextrose, Garlic and Onion, Guar Gum, Citric Acid, Beet Powder, Extractives of Paprika {Color}], Corn Oil), Pepperoni (Pork, Beef, Salt, Spices, Contains 2% or less of Dextrose, Lactic Acid Starter Culture, Flavorings, Garlic Powder, Sodium Nitrite, BHA, BHT, Citric Acid, Oleoresin of Paprika, and/or Paprika, May Also Contain Water, Smoke Flavoring, Sodium Ascorbate), Grated Parmesan Cheese (Pasteurized Part-Skim Milk, Cheese Cultures, Salt, Enzymes, Starch, Powdered Cellulose [to Prevent Caking]), Shredded Asiago Cheese (Asiago Cheese [Pasteurized Milk, Cheese Cultures, Salt, Enzymes] Powdered Cellulose [to Prevent Caking]), Seasoning (Spices [Oregano, Pepper, Basil], Maltodextrin, Onion & Garlic, Soybean Oil, Parsley).  ",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '4 servings per container',
                    'serving_size' => '1/4 pizza (123g)',
                    'calories' => 320,
                    'total_fat' => '18g',
                    'saturated_fat' => '8g',
                    'trans_fat' => '0g',
                    'cholesterol' => '50mg',
                    'sodium' => '660mg',
                    'total_carbohydrate' => '22g',
                    'dietary_fiber' => '2g',
                    'total_sugars' => '4g',
                    'added_sugars' => '0g',
                    'protein' => '14g',
                    'vitamin_d' => '0.3mcg',
                    'calcium' => '340mg',
                    'iron' => '1.4mg',
                    'potassium' => '320mg',
                ]
            ],
            [
                'name' => "Ultra Thin Crust Ultimate 5 Cheese",
                'slug' => "ultra-thin-crust-ultimate-5-cheese",
                'tags' => ['thin-crust', 'asiago', 'provolone', 'romano', 'fontina', 'cheese-lovers'],
                'description' => "Ultra Thin and Crispy pizza topped with Mozzarella, Asiago, Provolone, Romano and Fontina cheese, rich Italian sauce and Italian spices.",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/150/715/9998_Bel_UTC_5cheese_LR__67855.1588002923.jpg?c=2",
                'ingredients' => "Low Moisture Part Skim Mozzarella Cheese (Pasteurized Milk, Salt, Cheese Cultures, Enzymes), Crust (Wheat Flour[Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Soybean Oil, Dough Conditioner [Malted Barley Flour, Dextrose], Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid], Dextrose, Extra Virgin Olive Oil, Salt), Sauce (Water, Tomato Paste, Seasoning [Modified Food Starch, Sugar, Salt, Spices, Maltodextrin, Dextrose, Garlic & Onion, Guar Gum, Citric Acid, Beet Powder, Extractives of Paprika {Color}], Corn Oil), Four Cheese Blend (Low Moisture Part Skim Mozzarella Cheese [Cultured Pasteurized Part Skim Milk, Salt, Enzymes], Mild Asiago Cheese [Cultured Pasteurized Milk, Salt, Enzymes], Provolone Cheese with Smoke Flavor [Cultured Pasteurized Milk, Salt, Enzymes, Smoke Flavor], Romano Cheese [Cultured Pasteurized Part Skim Milk, Salt, Enzymes], Powdered Cellulose [to Prevent Caking], Natamycin [a Natural Mold Inhibitor]),  Fontina Cheese (Fontina Cheese [Pasteurized Milk, Cheese Culture, Salt, Enzymes], Powdered Cellulose [to Prevent Caking], Potassium Sorbate and Natamycin [Preservatives]), Parsley, Garlic, Seasoning (Spices [Oregano, Pepper, Basil], Maltodextrin, Onion & Garlic, Soybean Oil, Parsley).",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '3 servings per container',
                    'serving_size' => '1/3 pizza (129g)',
                    'calories' => 340,
                    'total_fat' => '16g',
                    'saturated_fat' => '8g',
                    'trans_fat' => '0g',
                    'cholesterol' => '45mg',
                    'sodium' => '580mg',
                    'total_carbohydrate' => '29g',
                    'dietary_fiber' => '2g',
                    'total_sugars' => '4g',
                    'added_sugars' => '1g',
                    'protein' => '19g',
                    'vitamin_d' => '0.2mcg',
                    'calcium' => '460mg',
                    'iron' => '0.7mg',
                    'potassium' => '310mg',
                ]
            ],
            [
                'name' => "Ultra Thin Crust Garlic Chicken Alfredo",
                'slug' => "ultra-thin-crust-garlic-chicken-alfredo",
                'tags' => ['thin-crust', 'garlic', 'chicken', 'alfredo', 'asiago',],
                'description' => "Ultra Thin and Crispy Pizza topped with Mozzarella, and Asiago cheese, creamy garlic Alfredo sauce, white meat chicken, and Italian spices.",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/153/728/9998_Bel_UTC_GarChxAlf_LR__68594.1588014612.jpg?c=2",
                'ingredients' => "Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Salt, Cheese Cultures, Enzymes), Crust (Wheat Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Soybean Oil, Dough Conditioner [Malted Barley Flour, Dextrose], Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid], Dextrose, Extra Virgin Olive Oil, Salt), Fully Cooked Seasoned Diced Boneless Chicken Breast (Boneless Chicken Breast Meat With Rib Meat, Water, Seasoning [Salt, Sugar, Spices <Onion Powder, Garlic Powder, Maltodextrin, Chili Powder (Salt, Cumin, Oregano, Garlic, Chili Pepper, Red Pepper, Natural Grill Flavor (Sunflower Oil, Tocopherol), Citric Acid>], Modified Potato Starch, Sodium Phosphate), Alfredo Sauce (Water, Seasoning [Whey, Parmesan and Cheddar Cheese Powder <Parmesan and Cheddar Cheese {Pasteurized Milk and Part-Skim Milk, Cheese Cultures, Salt, Enzymes}, Buttermilk, Whey, Salt, Disodium Phosphate, Soybean Oil, Citric Acid>, Corn Starch, Salt, Natural Flavors, Garlic Powder, Spices, Citric Acid, Less Than 2% Tricalcium Phosphate Added to Prevent Caking], Parmesan Cheese [Pasteurized Part-Skim Milk, Cheese Cultures, Salt, Enzymes, Starch and Powdered Cellulose to Prevent Caking]), Shredded Asiago Cheese (Asiago Cheese [Pasteurized Milk, Cheese Cultures, Salt, Enzymes] Powdered Cellulose [to Prevent Caking]), Minced Garlic, Seasoning (Spices [Oregano, Pepper, Basil], Maltodextrin, Onion & Garlic, Soybean Oil, Parsley), Parsley.",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '3 servings per container',
                    'serving_size' => '1/3 pizza (151g)',
                    'calories' => 360,
                    'total_fat' => '15g',
                    'saturated_fat' => '7g',
                    'trans_fat' => '0g',
                    'cholesterol' => '55mg',
                    'sodium' => '800mg',
                    'total_carbohydrate' => '32g',
                    'dietary_fiber' => '1g',
                    'total_sugars' => '4g',
                    'added_sugars' => '1g',
                    'protein' => '23g',
                    'vitamin_d' => '0.2mcg',
                    'calcium' => '460mg',
                    'iron' => '0.8mg',
                    'potassium' => '260mg',
                ]
            ],
            [
                'name' => "Gluten Free Pepperoni",
                'slug' => "gluten-free-pepperoni",
                'tags' => ['gluten-free', 'thin-crust', 'pepperoni', 'asiago',],
                'description' => "Bellatoria Gluten Free Pepperoni Pizza",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/212/696/9998_Bel_GF_Pep_LR__15191.1502123668.jpg?c=2",
                'ingredients' => "CRUST: WATER, BROWN RICE FLOUR, TAPIOCA FLOUR, MODIFIED RICE STARCH, FRESH YEAST, CANOLA/OLIVE OIL BLEND, SHORTENING FLAKES (PALM OIL, NATURAL BUTTER FLAVOR, AND SOY LECITHIN), WHEY POWDER, SUGAR, SALT, XANTHAN GUM, CALCIUM SULFATE (ADDED FOR FRESHNESS). MOZZARELLA CHEESE: PASTEURIZED PART-SKIM MILK, CHEESE CULTURES, SALT, ENZYMES. SAUCE: TOMATO PUREE (WATER, TOMATO PASTE), SALT, SPICES, SUGAR, ONION POWDER, GARLIC, CITRIC ACID. PEPPERONI: PORK AND BEEF, SALT, SPICES, DEXTROSE, LACTIC ACID STARTER CULTURE, OLEORESIN OF PAPRIKA, FLAVORING, SODIUM NITRITE, BHA, BHT, CITRIC ACID.",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '4 servings per container',
                    'serving_size' => '1/4 pizza (126g)',
                    'calories' => 300,
                    'total_fat' => '14g',
                    'saturated_fat' => '7g',
                    'trans_fat' => '0g',
                    'cholesterol' => '25mg',
                    'sodium' => '540mg',
                    'total_carbohydrate' => '30g',
                    'dietary_fiber' => '2g',
                    'total_sugars' => '2g',
                    'added_sugars' => '0g',
                    'protein' => '12g',
                    'vitamin_d' => '0mcg',
                    'calcium' => '6%',
                    'iron' => '6%',
                ]
            ],
            [
                'name' => "Gluten Free Cheese",
                'slug' => "gluten-free-cheese",
                'tags' => ['gluten-free', 'thin-crust', 'cheese-lovers'],
                'description' => "Bellatoria Gluten Free Cheese Pizza",
                'image_url' => "http://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/211/695/9998_Bel_GF_Cheese_LR__09044.1502123269.jpg?c=2",
                'ingredients' => "CRUST: WATER, BROWN RICE FLOUR, TAPIOCA FLOUR, MODIFIED RICE STARCH, FRESH YEAST, CANOLA/OLIVE OIL BLEND, SHORTENING FLAKES (PALM OIL, NATURAL BUTTER FLAVOR, AND SOY LECITHIN), WHEY POWDER, SUGAR, SALT, XANTHAN GUM, CALCIUM SULFATE (ADDED FOR FRESHNESS). MOZZARELLA CHEESE: PASTEURIZED PART-SKIM MILK, CHEESE CULTURES, SALT, ENZYMES. SAUCE: TOMATO PUREE (WATER, TOMATO PASTE), SALT, SPICES, SUGAR, ONION POWDER, GARLIC, CITRIC ACID.",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '4 servings per container',
                    'serving_size' => '1/4 pizza (178g)',
                    'calories' => 280,
                    'total_fat' => '12g',
                    'saturated_fat' => '6g',
                    'trans_fat' => '0g',
                    'cholesterol' => '20mg',
                    'sodium' => '430mg',
                    'total_carbohydrate' => '31g',
                    'dietary_fiber' => '3g',
                    'total_sugars' => '2g',
                    'added_sugars' => '0g',
                    'protein' => '13g',
                    'vitamin_d' => '0mcg',
                    'calcium' => '30%',
                    'iron' => '6%',
                ]
            ],
            [
                'name' => "Ultra Thin Crust Hawaiian Style BBQ",
                'slug' => "ultra-thin-crust-hawaiian-style-bbq",
                'tags' => ['thin-crust', 'bbq', 'pineapple', 'canadian-bacon', 'ham', 'bbq', 'asiago', 'cheese-lovers', 'hawaiian',],
                'description' => "Ultra Thin and Crispy Pizza topped with Mozzarella, Parmesan, Asiago cheese, BBQ Sauce, Pineapple, Canadian style bacon, cooked diced ham & Italian spices.",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/154/712/9998_Bel_UTC_HawaiiBBQ_LR__04653.1588000667.jpg?c=2",
                'ingredients' => "Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Salt, Cheese Cultures, Enzymes), Crust (Wheat Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Soybean Oil, Dough Conditioner [Malted Barley Flour, Dextrose], Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid], Dextrose, Extra Virgin Olive Oil, Salt), Sweet Hickory BBQ Sauce (Sugar, Water, Tomato Paste, Vinegar, Salt, Pineapple Juice Concentrate, Food Starch-Modified, Worcestershire Sauce [Water, Salt, Vinegar, Sugar, Malic Acid, Molasses, Citric Acid, Dehydrated Onion and Garlic, Food Gums {Arabic, Xanthan, Guar, Cellulose}, Spices, Dextrose, Natural Flavors, Smoke Flavor], Liquid Smoke, Mustard Flour, Spices, Sodium Benzoate as a Preservative), Pineapple, Canadian Style Bacon (Pork, Water, Salt, Brown Sugar, Potassium Lactate, Sodium Lactate, Sodium Phosphate, Sodium Diacetate, Sodium Erythorbate, Sodium Nitrite), Fully Cooked Diced Smoked Ham with Natural Juices (Pork Cured with Water, Salt, Dextrose, Sodium Phosphate, Sodium Erythorbate, Sodium Nitrite), Parmesan Cheese (Pasteurized Part-Skim Milk, Cheese Cultures, Salt, Enzymes, Starch and Powdered Cellulose to Prevent Caking), Shredded Asiago Cheese (Asiago Cheese [Pasteurized Milk, Cheese Cultures, Salt, Enzymes] Powdered Cellulose [to Prevent Caking]), Seasoning (Spices [Oregano, Pepper, Basil], Maltodextrin, Onion & Garlic, Soybean Oil, Parsley), Parsley. ",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '3 servings per container',
                    'serving_size' => '1/3 pizza (159g)',
                    'calories' => 380,
                    'total_fat' => '14g',
                    'saturated_fat' => '7g',
                    'trans_fat' => '0g',
                    'cholesterol' => '45mg',
                    'sodium' => '850mg',
                    'total_carbohydrate' => '44g',
                    'dietary_fiber' => '2g',
                    'total_sugars' => '17g',
                    'added_sugars' => '12g',
                    'protein' => '21g',
                    'vitamin_d' => '0.2mcg',
                    'calcium' => '30%',
                    'iron' => '6%',
                    'potassium' => '380mg',
                    'monounsaturated_fat' => '',
                    'polyunsaturated_fat' => '',
                    'vitamin_a' => '',
                    'vitamin_c' => '',
                ]
            ],
            [
                'name' => "Sunday Brunch Sausage Scramble",
                'slug' => "sunday-brunch-sausage-scramble",
                'tags' => ['breakfast', 'sausage', 'eggs', 'cheddar'],
                'description' => "Our Bellatoria Sunday Brunch Pizza includes scrambled eggs, country-style gravy, mozzarella and cheddar cheese on a golden, biscuit-style, including zesty sausage!",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/233/820/00039131168983_SM1_23032021__96082.1736360718.jpg?c=2",
                'ingredients' => "Toppings: Creamy White Gravy (Water, Modified Corn Starch, Cream Powder, Coconut Oil, Corn Syrup Solids, Sodium Caseinate, Dipotassium Phosphate, Mono & Diglycerides, Nonfat Dry Milk, Salt, Dextrose, Maltodextrin, Whey, Natural Flavors Including Butter, Spice, Onion Powder, Autolyzed Yeast Extract), Scrambled Eggs (Whole Eggs, Skim Milk, Soybean Oil, Corn Starch, Salt, Citric Acid, Cheese [Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Cheese Cultures, Salt, Enzymes), Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes)], Cooked Sausage (Pork, Water, Salt, Spices, Dextrose, Autolyzed Yeast Extract, Flavoring, Garlic Powder), Biscuit Style Crust (Wheat Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme], Water, Shortening, Sugar, Salt, Yeast, Dough Conditioner [Whey, L-Cysteine Hydrochloride, Calcium Propionate (Mold Inhibitor)])",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '3 servings per container',
                    'serving_size' => '1/3 pizza (136g)',
                    'calories' => 370,
                    'total_fat' => '19g',
                    'saturated_fat' => '7g',
                    'trans_fat' => '0g',
                    'cholesterol' => '80mg',
                    'sodium' => '700mg',
                    'total_carbohydrate' => '37g',
                    'dietary_fiber' => '5g',
                    'total_sugars' => '2g',
                    'added_sugars' => '',
                    'protein' => '14g',
                    'vitamin_d' => '',
                    'calcium' => '20%',
                    'iron' => '15%',
                    'vitamin_a' => '8%',
                ]
            ],
            [
                'name' => "Sunday Brunch Bacon Scramble",
                'slug' => "sunday-brunch-bacon-scramble",
                'tags' => ['breakfast', 'bacon', 'eggs', 'cheddar'],
                'description' => "Our Bellatoria Sunday Brunch Pizza includes scrambled eggs, country-style gravy, mozzarella and cheddar cheese on a golden, biscuit-style, including smoked bacon!",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/234/824/00039131168976_SM1_23032021__75103.1736360801.jpg?c=2",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '3 servings per container',
                    'serving_size' => '1/3 pizza (132g)',
                    'calories' => 370,
                    'total_fat' => '18g',
                    'saturated_fat' => '7g',
                    'trans_fat' => '0g',
                    'cholesterol' => '85mg',
                    'sodium' => '740mg',
                    'total_carbohydrate' => '37g',
                    'dietary_fiber' => '4g',
                    'total_sugars' => '2g',
                    'added_sugars' => '',
                    'protein' => '15g',
                    'vitamin_d' => '',
                    'calcium' => '20%',
                    'iron' => '15%',
                    'potassium' => '',
                    'monounsaturated_fat' => '',
                    'polyunsaturated_fat' => '',
                    'vitamin_a' => '6%',
                    'vitamin_c' => '0%',
                ]
            ],
        ];

        foreach ($pizzas as $pizza) {
            PizzaSeedHandler::seedPizza($brand, $pizza);
        }
    }
}
