<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Brand;
use App\Handlers\ImageHandler;
use App\Handlers\PizzaSeedHandler;

class BrewPubSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $brand = Brand::updateOrCreate([
            'slug' => 'brewpub',
        ], [
            'name' => 'BrewPub',
            'website' => 'https://www.shopbernatellospizza.com/brew-pub/',
            'brand_story' => 'Brew Pub is Bernatello’s Foods’ premium frozen pizza brand—a bold, upscale entry designed to bring the hearty, indulgent flavors of a traditional brewpub right to your freezer. Launched as part of Bernatello’s strategy to modernize and expand its portfolio, Brew Pub pizzas are crafted with twice the cheese and generous helpings of classic pizza meats, including even a bacon cheeseburger variation. The brand aims to deliver a restaurant-quality, meat-forward experience that pairs perfectly with a cold brew, capturing the nostalgic essence of a neighborhood brewpub while embracing innovative frozen pizza production techniques.',
            'brand_story' => "Brew Pub was born from Bernatello’s Foods’ rich history of frozen pizza innovation. As Bernatello’s evolved from its early days in the 1980s—when it first gained a reputation for quality frozen pizzas—the company began to explore premium product lines to meet changing consumer tastes. Recognizing the growing demand for a frozen pizza that could deliver the robust, hearty flavors of a neighborhood brewpub, Bernatello’s developed Brew Pub. This brand was designed to capture the essence of traditional brewpub fare with extra layers of cheese, bold, savory toppings, and even a bacon cheeseburger-inspired variation. Brew Pub represents the fusion of time-honored recipes with modern production techniques, a nod to both the company’s past successes and its innovative spirit moving forward.",
            'founded_year' => '2012',
            'description' => 'Brew Pub is Bernatello’s Foods’ premium frozen pizza brand, proudly crafted in Maple Lake, Minnesota. It features a rich, meat-forward style with twice the cheese and generous portions of classic pizza meats—including a unique bacon cheeseburger option—delivering the indulgent flavors of a traditional brewpub right from your freezer.',
        ]);

        if (!$brand->image) {
            $image = ImageHandler::createFromUrl(
                'https://www.shopbernatellospizza.com/product_images/uploaded_images/brewpub-brandmark.jpg', // url
                'public',
                'images/logos/frozen',
                'BrewPub' // name - no extension
            );
            $brand->image_id = $image?->id ?? null;
            $brand->save();
        }

        $pizzas = [
            [
                'name' => "Lotzza Motzza Sausage & Pepperoni",
                'slug' => "lotzza-motzza-sausage-pepperoni",
                'tags' => ['pepperoni', 'sausage'],
                'description' => "Fresh tomato sauce, large nuggets of zesty sausage, flavorful pepperoni slices and over 1/2 of real Wisconsin Mozzarella Cheese!",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/146/794/LotzzaMotzza_SausagePepperoni_f__66303.1680029918.png?c=2",
                'ingredients' => "Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Salt, Cheese Cultures, Enzymes), Crust (Enriched Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Lard [Lard, BHA, Propyl Gallate with Citric Acid Added to Help Protect Flavor], Dough Conditioner [Malted Barley Flour, Dextrose], Salt, Sugar, Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid]), Sauce (Tomato Puree, Water, Seasoning [Salt, Spices, Sugar, Garlic Powder], Romano Cheese Made from Cow's Milk [Pasteurized Milk, Cheese Cultures, Salt, Enzymes]), Cooked Italian Sausage (Pork, Spices, Salt, Dextrose, Garlic Powder, Paprika, Flavoring), Pepperoni (Pork, Beef, salt, Spices, Contains 2% or less of Dextrose, Lactic Acid Starter Culture, Flavorings, Garlic Powder, Sodium Nitrite, BHA, BHT, Citric Acid, Oleoresin of Paprika, and/or Paprika, May also contain Water, Smoke Flavoring, Sodium Ascorbate). ",
                'allergens' => "Wheat, Milk, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => 5,
                    'serving_fraction' => '1/5',
                    'serving_weight' => 152,
                    'calories' => 380,
                    'caloris_from_fat' => 0,
                    'total_fat' => 16,
                    'saturated_fat' => 6,
                    'trans_fat' => 0,
                    'cholesterol' => 35,
                    'sodium' => 710,
                    'total_carbohydrate' => 41,
                    'dietary_fiber' => 2,
                    'total_sugars' => 3,
                    'added_sugars' => 0,
                    'protein' => 17,
                    'vitamin_d' => 0.2,
                    'calcium' => 310,
                    'iron' => 1.3,
                    'potassium' => 330,
                ]
            ],
            [
                'name' => "Lotzza Motzza Pepperoni",
                'slug' => "lotzza-motzza-pepperoni",
                'tags' => ['pepperoni'],
                'description' => "Fresh tomato sauce, flavorful pepperoni slices, diced pepperoni pieces, and over 1/2 pound of Real Wisconsin Mozzarella Cheese!",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/144/798/LotzzaMotzza_Pepperoni_f__04921.1680030696.png?c=2",
                'ingredients' => "Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Salt, Cheese Cultures, Enzymes), Crust (Enriched Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Lard [Lard, BHA, Propyl Gallate with Citric Acid Added to Help Protect Flavor], Dough Conditioner (Malted Barley Flour, Dextrose), Salt, Sugar, Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid), Sauce (Tomato Puree, Water, Seasoning [Salt, Spices, Sugar, Garlic Powder], Romano Cheese Made from Cow's Milk [Pasteurized Milk, Cheese Cultures, Salt, Enzymes]), Pepperoni (Pork, Beef, salt, Spices, Contains 2% or less of Dextrose, Lactic Acid Starter Culture, Flavorings, Garlic Powder, Sodium Nitrite, BHA, BHT, Citric Acid, Oleoresin of Paprika, and/or Paprika, May also contain Water, Smoke Flavoring, Sodium Ascorbate). ",
                'allergens' => "Wheat, Milk, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => 4,
                    'serving_fraction' => '1/4',
                    'serving_weight' => 149,
                    'calories' => 380,
                    'caloris_from_fat' => 0,
                    'total_fat' => 18,
                    'saturated_fat' => 9,
                    'trans_fat' => 0,
                    'cholesterol' => 45,
                    'sodium' => 900,
                    'total_carbohydrate' => 35,
                    'dietary_fiber' => 2,
                    'total_sugars' => 4,
                    'added_sugars' => 0.5,
                    'protein' => 16,
                    'vitamin_d' => 0.3,
                    'calcium' => 400,
                    'iron' => 2.2,
                    'potassium' => 380,
                ]
            ],
            [
                'name' => "Lotzza Motzza Sausage",
                'slug' => "lotzza-motzza-sausage",
                'tags' => ['sausage'],
                'description' => "Fresh tomato sauce, large nuggets of zesty sausage, and over 1/2 pound of Real Wisconsin Mozzarella Cheese!",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/143/800/LotzzaMotzza_Sausage_f__37797.1680030863.png?c=2",
                'ingredients' => "Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Salt,  Cheese Cultures, Enzymes), Crust (Enriched Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Lard [Lard, BHA, Propyl Gallate with Citric Acid Added to Help Protect Flavor], Dough Conditioner [Malted Barley Flour, Dextrose], Salt, Sugar, Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid]), Sauce (Tomato Puree, Water, Seasoning [Salt, Spices, Sugar, Garlic Powder], Romano Cheese Made from Cow's Milk [Pasteurized Milk, Cheese Cultures, Salt, Enzymes]), Cooked Italian Sausage (Pork, Spices, Salt, Dextrose, Garlic Powder, Paprika, Flavoring). ",
                'allergens' => "Wheat, Milk, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => 5,
                    'serving_fraction' => '1/5',
                    'serving_weight' => 134,
                    'calories' => 330,
                    'caloris_from_fat' => 0,
                    'total_fat' => 16,
                    'saturated_fat' => 8,
                    'trans_fat' => 0,
                    'cholesterol' => 45,
                    'sodium' => 770,
                    'total_carbohydrate' => 28,
                    'dietary_fiber' => 2,
                    'total_sugars' => 4,
                    'added_sugars' => 0.5,
                    'protein' => 15,
                    'vitamin_d' => 0.4,
                    'calcium' => 330,
                    'iron' => 1.9,
                    'potassium' => 350,
                ]
            ],
            [
                'name' => "Lotzza Motzza Cheese",
                'slug' => "lotzza-motzza-cheese",
                'tags' => ['cheese-lovers', 'chedar', 'vegetarian'],
                'description' => "Fresh tomato sauce, white cheddar cheese, and over 1/2 pound of Real Wisconsin Mozzarella Cheese!",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/145/796/LotzzaMotzza_Cheese_f__55673.1680030497.png?c=2",
                'ingredients' => "Low Moisture Part Skim Mozzarella Cheese (Pasteurized Milk, Salt, Cheese Cultures, Enzymes), Crust (Wheat Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Lard [Lard, BHA, Propyl Gallate with Citric Acid Added to Help Protect Flavor], Dough Conditioner [Malted Barley Flour, Dextrose], Salt, Sugar, Yeast [Yeast, Sorbitan, Monostearate, Ascorbic Acid]), Sauce (Tomato Puree, Water, Seasoning [Salt, Spices, Sugar, Garlic Powder], Romano Cheese [Pasteurized Cows Milk, Cheese Cultures, Salt, Enzymes]). ",
                'allergens' => "Wheat, Milk, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => 4,
                    'serving_fraction' => '1/4',
                    'serving_weight' => 142,
                    'calories' => 340,
                    'caloris_from_fat' => 0,
                    'total_fat' => 14,
                    'saturated_fat' => 8,
                    'trans_fat' => 0,
                    'cholesterol' => 40,
                    'sodium' => 760,
                    'total_carbohydrate' => 35,
                    'dietary_fiber' => 2,
                    'total_sugars' => 4,
                    'added_sugars' => 0.5,
                    'protein' => 15,
                    'vitamin_d' => 0.2,
                    'calcium' => 430,
                    'iron' => 2.1,
                    'potassium' => 350,
                ]
            ],
            [
                'name' => "Lotzza Motzza Supreme",
                'slug' => "lotzza-motzza-supreme",
                'tags' => ['supreme', 'pepperoni', 'sausage', 'peppers', 'onions', 'mushroom'],
                'description' => "Fresh tomato sauce, large nuggets of zesty sausage, flavorful pepperoni slices, premium green and red peppers, onions, mushrooms, and With over 1/2 of real Wisconsin Mozzarella Cheese!",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/147/792/LotzzaMotzza_Supreme_f__09336.1680029674.png?c=2",
                'ingredients' => "Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Salt, Cheese Cultures,Enzymes), Crust (Enriched Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Lard [Lard, BHA, Propyl Gallate with Citric Acid Added to Help Protect Flavor], Dough Conditioner [Malted Barley Flour, Dextrose], Salt, Sugar, Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid]), Sauce (Tomato Puree, Water, Seasoning [Salt, Spices, Sugar, Garlic Powder], Romano Cheese Made from Cow's Milk [Pasteurized Milk, Cheese Cultures, Salt, Enzymes]), Cooked Italian Sausage (Pork, Spices, Salt, Dextrose, Garlic Powder, Paprika, Flavoring), Fire Roasted Vegetable Blend (Red Bell Pepper, Green Bell Pepper, Red Onion), Mushrooms, Pepperoni (Pork, Beef, salt, Spices, Contains 2% or less of Dextrose, Lactic Acid Starter Culture, Flavorings, Garlic Powder, Sodium Nitrite, BHA, BHT, Citric Acid, Oleoresin of Paprika, and/or Paprika, May also contain Water, Smoke Flavoring, Sodium Ascorbate).",
                'allergens' => "Wheat, Milk, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => 4,
                    'serving_fraction' => '1/4',
                    'serving_weight' => 142,
                    'calories' => 320,
                    'caloris_from_fat' => 0,
                    'total_fat' => 12,
                    'saturated_fat' => 6,
                    'trans_fat' => 0,
                    'cholesterol' => 30,
                    'sodium' => 700,
                    'total_carbohydrate' => 30,
                    'dietary_fiber' => 2,
                    'total_sugars' => 3,
                    'added_sugars' => 0.5,
                    'protein' => 14,
                    'vitamin_d' => 0.1,
                    'calcium' => 400,
                    'iron' => 1.5,
                    'potassium' => 300,
                    'monounsaturated_fat' => 3,
                    'polyunsaturated_fat' => 1,
                    'vitamin_a' => 200,
                    'vitamin_c' => 2,
                ]
            ],
            [
                'name' => " Lotzza Motzza 4 Meat",
                'slug' => "lotzza-motzza-4-meat",
                'tags' => ['meat-lovers', 'bacon', 'pepperoni', 'sausage', 'canadian-bacon'],
                'description' => "Fresh tomato sauce, large nuggets of zesty sausage, flavorful slices of pepperoni, Canadian style bacon, bacon pieces, and over 1/2 lb of real Wisconsin Mozzarella Cheese!",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/148/790/LotzzaMotzza_4Meat_f__96612.1680023162.png?c=2",
                'ingredients' => "Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Salt, Cheese Cultures, Enzymes), Crust (Enriched Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Lard [Lard, BHA, Propyl Gallate with Citric Acid Added to Help Protect Flavor], Dough Conditioner [Malted Barley Flour, Dextrose], Salt, Sugar, Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid]), Sauce (Tomato Puree, Water, Seasoning [Salt, Spices, Sugar, Garlic Powder], Romano Cheese Made from Cow's Milk [Pasteurized Milk, Cheese Cultures, Salt, Enzymes]), Cooked Italian Sausage (Pork, Spices, Salt, Dextrose, Garlic Powder, Paprika, Flavoring),Bacon (Pork Cured with: Water, Salt, Sodium Phosphate, Sodium Erythorbate, Sodium Nitrite. May Also Contain Sugar, Flavoring, Smoke Flavor, Brown Sugar),Pepperoni (Pork, Beef, salt, Spices, Contains 2% or less of Dextrose, Lactic Acid Starter Culture, Flavorings, Garlic Powder, Sodium Nitrite, BHA, BHT, Citric Acid, Oleoresin of Paprika, and/or Paprika, May also contain Water, Smoke Flavoring, Sodium Ascorbate), Canadian Style BaconMade With Pork Sirloin Hips (Pork, Water, Salt, Brown Sugar, Potassium Lactate, Sodium Lactate, Sodium Phosphate, Sodium Diacetate, Sodium Erythorbate, Sodium Nitrite). ",
                'allergens' => "Wheat, Milk, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => 5,
                    'serving_fraction' => '1/5',
                    'serving_weight' => 138,
                    'calories' => 360,
                    'caloris_from_fat' => 0,
                    'total_fat' => 18,
                    'saturated_fat' => 8,
                    'trans_fat' => 0,
                    'cholesterol' => 50,
                    'sodium' => 920,
                    'total_carbohydrate' => 28,
                    'dietary_fiber' => 2,
                    'total_sugars' => 4,
                    'added_sugars' => 0.5,
                    'protein' => 17,
                    'vitamin_d' => 0.3,
                    'calcium' => 330,
                    'iron' => 2,
                    'potassium' => 390,
                ]
            ],
            [
                'name' => "Lotzza Motzza Breakfast",
                'slug' => "lotzza-motzza-breakfast",
                'tags' => ['breakfast', 'bacon', 'sausage', 'eggs', 'cheddar'],
                'description' => "BrewPub Lotzza Motzza Breakfast Pizza",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/220/791/LotzzaMotzza_BreakfastPizza_f__55832.1680023297.png?c=2",
                'ingredients' => "Crust (Enriched Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Lard [Lard, BHA, Propyl Gallate with Citric Acid Added to Help Protect Flavor], Dough Conditioner [Malted Barley Flour, Dextrose], Salt, Sugar, Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid]), Low Moisture Part Skim MozzarellaCheese (Pasteurized Part Skim Milk, Salt, Cheese Cultures, Enzymes), Scrambled Eggs (Whole Eggs, Skim Milk, Soybean Oil, Corn Starch, Salt, Xanthan Gum, Citric Acid), Country Gravy (Water, Seasoning [Modified Corn Starch, Cream Powder {Coconut Oil, Corn Syrup Solids, Sodium Caseinate, Dipotassium Phosphate, Mono & Diglycerides}, Nonfat Dry Milk, Salt, Dextrose, Maltodextrin, Whey, Natural Flavors Including Butter, Spice, Onion Powder, Autolyzed Yeast Extract, Torula Yeast, Hydrolyzed Corn Protein, Disodium Inosinate and Guanylate, Chicken Fat]), CookedSausage (Pork, Spices, Water, Salt, and Less Than 2% of the Following: Dextrose, Paprika, Garlic Powder, Yeast Extract, Natural Flavorings, Potassium Chloride, Sodium Tripolyphosphate), Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Annatto [Color]),Fully Cooked Bacon  (Pork, Cured with: Water, Salt, Sodium Phosphate, Sodium Erythorbate, Sodium Nitrite. May Contain Sugar, Flavoring, Smoke Flavor, Brown Sugar). ",
                'allergens' => "Wheat, Milk, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => 5,
                    'serving_fraction' => '1/5',
                    'serving_weight' => 138,
                    'calories' => 370,
                    'caloris_from_fat' => 0,
                    'total_fat' => 20,
                    'saturated_fat' => 9,
                    'trans_fat' => 0,
                    'cholesterol' => 125,
                    'sodium' => 840,
                    'total_carbohydrate' => 27,
                    'dietary_fiber' => 1,
                    'total_sugars' => 2,
                    'added_sugars' => 0.5,
                    'protein' => 16,
                    'vitamin_d' => 0.3,
                    'calcium' => 330,
                    'iron' => 1.8,
                    'potassium' => 260,
                ]
            ],
            [
                'name' => "Packers - The Pick 6",
                'slug' => "packers-the-pick-6",
                'tags' => ['sausage', 'ham', 'beef', 'pepperoni', 'canadian-bacon', 'bacon'],
                'description' => "The Pick-6 pizza is the perfect combination of 6 meats - sausage, diced ham, pepperoni, beef, Canadian style bacon, and bacon bits - bombarded with our classic Brew Pub sauce and award-winning Wisconsin mozzarella cheese. Brew Pub pizza and the Green Bay Packers are a winning combination that can't be beat! Brew Pub Pizza is the Official Pizza of the Green Bay Packers!",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/232/817/BP_Packers_The_Pick_6-01__54574.1719598757.png?c=2",
                'ingredients' => "Crust (Enriched Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamin Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Lard [Lard, BHA Propyl Gallate with Citric Acid Added to Help Protect Flavor], Dough Conditioner [Malted Barley Flour, Dextrose], Salt, Sugar, Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid]), Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Salt, Cheese Cultures, Enzymes), Sauce (Tomato Puree, Water, Seasoning [Salt, Spices, Sugar, Garlic Powder], Romano Cheese Made from Cow's Milk [Pasteurized Milk, Cheese Cultures, Salt, Enzymes]), Cooked Italian Sausage (Pork, Spices, Salt, Dextrose, Garlic Powder, Paprika, Flavoring), Fully Cooked Diced Smoked Ham with Natural Juices (Pork Cured with Water, Salt, Dextrose, Sodium Phosphate, Sodium Erythorbate, Sodium Nitrite), Beef Water and Binder Product (Beef, Water, Dextrose, Salt, Sodium Phosphates, Modified Food Starch, Sodium Citrate, Hydrolyzed Corn Protein, Autolyzed Yeast Extract, Caramel Color, Sodium Diacetate, Spices [Including Celery Seed], Onion and Garlic Powder, Guar Gum, Paprika, Maltodextrin, Corn Syrup Solids, Natural Smoke Flavor), Pepperoni (Pork, Beef, Salt, Spices, Contains 2% or Less of Dextrose, Lactic Acid Starter Culture, Flavorings, Garlic Powder, Sodium Nitrite, BHA, BHT, Citric Acid, Oleoresin of Paprika, and/or Paprika, May Also Contain Water, Smoke Flavoring, Sodium Ascorbate), Canadian Style Bacon Made with Pork Sirloin Hips (Pork, Water, Salt, Brown Sugar, Potassium Lactate, Sodium Lactate, Sodium Phosphate, Sodium Diacetate, Sodium Erythorbate, Sodium Nitrite), Fully Cooked Bacon Topping (Pork Cured with Water, Salt, Sodium Phosphate, Sodium Erythorbate, Sodium Nitrite, May Also Contain Sugar, Flavoring, Smoke Flavor, Brown Sugar).",
                'allergens' => "Wheat, Milk, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => 5,
                    'serving_fraction' => '1/5',
                    'serving_weight' => 135,
                    'calories' => 330,
                    'caloris_from_fat' => 0,
                    'total_fat' => 16,
                    'saturated_fat' => 7,
                    'trans_fat' => 0,
                    'cholesterol' => 45,
                    'sodium' => 910,
                    'total_carbohydrate' => 28,
                    'dietary_fiber' => 2,
                    'total_sugars' => 4,
                    'added_sugars' => 1,
                    'protein' => 15,
                    'vitamin_d' => 0.3,
                    'calcium' => 260,
                    'iron' => 2,
                    'potassium' => 380,
                ]
            ],
            [
                'name' => "Packers - The Kicker",
                'slug' => "packers-the-kicker",
                'tags' => ['jalapeno', 'bacon', 'asiago', 'garlic'],
                'description' => "The Kicker is a Jalapeno Popper pizza topped with Jalapeno Cream cheese sauce, then loaded with mozzarella and asiago cheeses, bacon, jalapeno peppers and garlic. Brew Pub pizza and the Green Bay Packers are a winning combination that can't be beat! Brew Pub Pizza is the Official Pizza of the Green Bay Packers!",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/231/815/BP_Packers_The_Kicker-01__15006.1719598657.png?c=2",
                'ingredients' => "Crust (Enriched Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamin Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Lard [Lard, BHA, Propyl Gallate with Citric Acid Added to Help Protect Flavor], Dough Conditioner [Malted Barley Flour, Dextrose], Salt, Sugar, Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid]), Jalapeno Cream Cheese Sauce (Water, [Cream Cheese {Pasteurized Milk and Cream, Cheese Culture, Salt, Carob Bean Gum}, Sour Cream Powder {Cream, Cultures and Lactic Acid}, Modified Food Starch, Whey, Nonfat Milk, Sugar, Less than 2% of Spices, Salt, Sodium Phosphate, Citric Acid, and Fully Refined Soybean Oil]), Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Salt, Cheese Cultures, Enzymes), Fully Cooked Bacon Topping (Pork Cured with Water, Salt, Sodium Phosphate, Sodium Erythorbate, Sodium Nitrite, May Also Contain Sugar, Flavoring, Smoke Flavor, Brown Sugar), Jalapeno Pepper, Shredded Asiago Cheese (Asiago Cheese [Pasteurized Milk, Cheese Cultures, Salt, Enzymes] Powdered Cellulose [to Prevent Caking]), Minced Garlic.",
                'allergens' => "Wheat, Milk, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => 4,
                    'serving_fraction' => '1/4',
                    'serving_weight' => 146,
                    'calories' => 400,
                    'caloris_from_fat' => 0,
                    'total_fat' => 21,
                    'saturated_fat' => 11,
                    'trans_fat' => 0.5,
                    'cholesterol' => 60,
                    'sodium' => 900,
                    'total_carbohydrate' => 34,
                    'dietary_fiber' => 1,
                    'total_sugars' => 4,
                    'added_sugars' => 1,
                    'protein' => 15,
                    'vitamin_d' => 0.4,
                    'calcium' => 320,
                    'iron' => 2,
                    'potassium' => 290,
                ]
            ],
            [
                'name' => "Packers - Stadium Steak",
                'slug' => "packers-stadium-steak",
                'tags' => ['cheesesteak', 'beef', 'peppers', 'onions', 'provolone'],
                'description' => "The Stadium Steak pizza is a Philly Style Cheesesteak pizza, topped with a perfect combination of cheese sauce, beef topping, red and green peppers, red onion, mozzarella and provolone cheeses. Brew Pub pizza and the Green Bay Packers are a winning combination that can't be beat! Brew Pub Pizza is the Official Pizza of the Green Bay Packers!",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/229/811/BP_Packers_Stadium_Steak-01__09864.1719598395.png?c=2",
                'ingredients' => "Crust (Enriched Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thamin Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Lard [Lard, BHA Propyl Gallate with Citric Acid Added to Help Protect Flavor], Dough Conditioner [Malted Barley Flour, Dextrose] Salt, Sugar, Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid]), Cheddar Cheese Sauce [Water, Instant Cheese Sauce (Whey, Maltodextrin, Dehydrated Cheddar Cheese [Pasteurized Milk, Cheese Culture, Salt, Enzymes], Modified Corn Starch, Salt, Dry Whole Milk, Buttermilk Powder Sodium Phosphate, Lactic Acid, Natural Flavors, Dehydrated Butter, Extractives of Annatto [Color], Turmeric [Color]) Beef Water and Binder Product (Beef, Water, Dextrose, Salt, Sodium Phosphates, Modified Food Starch, Sodium Citrate, Hydrolyzed Corn Protein, Autolyzed Yeast Extract, Caramel Color, Sodium Diacetate, Spices [Including Celery Seed], Onion and Garlic Powder Guar Gum, Paprika, Maltodextrin, Corn Syrup Solids, Natural Smoke Flavor) Provolone Cheese (Pasteurized Whole Milk Cheese Culture, Salt, Enzymes), Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Salt, Cheese Cultures, Enzymes), Fire Roasted Vegetable Blend (Red Bell Pepper, Green Bell Pepper Red Onion), Seasoning (Salt, Black Pepper, Garlic Powder).",
                'allergens' => "Wheat, Milk, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => 4,
                    'serving_fraction' => '1/4',
                    'serving_weight' => 144,
                    'calories' => 370,
                    'caloris_from_fat' => 0,
                    'total_fat' => 18,
                    'saturated_fat' => 9,
                    'trans_fat' => 0,
                    'cholesterol' => 45,
                    'sodium' => 970,
                    'total_carbohydrate' => 36,
                    'dietary_fiber' => 1,
                    'total_sugars' => 4,
                    'added_sugars' => 1,
                    'protein' => 12,
                    'vitamin_d' => 0,
                    'calcium' => 300,
                    'iron' => 1.7,
                    'potassium' => 180,
                ]
            ],
            [
                'name' => "Packers - BBQ Blitz",
                'slug' => "packers-bbq-blitz",
                'tags' => ['bbq', 'chicken', 'cheddar', 'corn-chips',],
                'description' => "The BBQ Blitz pizza is made with generous amounts of BBQ Smoked Chicken, smothered in sweet, tangy BBQ sauce, and smothered with mozzarella and cheddar cheeses, green onions and corn chips. Brew Pub pizza and the Green Bay Packers are a winning combination that can't be beat! Brew Pub Pizza is the Official Pizza of the Green Bay Packers!",
                'image_url' => "https://cdn11.bigcommerce.com/s-5tf6tdwuxj/images/stencil/1280x1280/products/230/813/BP_Packers_BBQ_Blitz-01__18418.1719598566.png?c=2",
                'ingredients' => "Crust (Enriched Flour [Bleached Wheat Flour, Niacin, Reduced Iron, Thiamin Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Lard [Lard, BHA, Propyl Gallate with Citric Acid Added to Help Protect Flavor], Dough Conditioner [Malted Barley Flour, Dextrose], Salt, Sugar, Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid]), Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Salt, Cheese Cultures, Enzymes), Bbq Sauce (Sugar, Water, Tomato Paste, Vinegar, Salt, Pineapple Juice Concentrate, Modified Food Starch, Worcestershire Sauce [Water, Salt, Vinegar, Sugar, Malic Acid, Molasses, Citric Acid, Dehydrated Onion and Garlic, Food Gums {Arabic, Xanthan, Guar, Cellulose}, Spices, Dextrose, Natural Flavors, Smoke Flavor], Liquid Smoke, Mustard Flour, Spices, Sodium Benzoate as a Preservative), Smoked Pulled Chicken (Chicken, Seasoning [Spices, Salt, Sugar, Garlic Powder, Disodium Inosinate and Disodium Guanylate, Silicon Dioxide and Sunflower Oil {to Prevent Caking}], Less than 2% of Potassium Lactate, Water, Sodium Diacetate, Natural Hickory Wood Smoke Flavor), Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Annatto [Color]), Corn Chips (Corn, Corn Oil, and Salt), Green Onion.",
                'allergens' => "",
                'nutritional_facts' => [
                    'serving_per_container' => 4,
                    'serving_fraction' => '1/4',
                    'serving_weight' => 151,
                    'calories' => 410,
                    'caloris_from_fat' => 0,
                    'total_fat' => 16,
                    'saturated_fat' => 7,
                    'trans_fat' => 0,
                    'cholesterol' => 60,
                    'sodium' => 950,
                    'total_carbohydrate' => 47,
                    'dietary_fiber' => 2,
                    'total_sugars' => 14,
                    'added_sugars' => 11,
                    'protein' => 17,
                    'vitamin_d' => 0.3,
                    'calcium' => 310,
                    'iron' => 2.2,
                    'potassium' => 400,
                ]
            ],
            [
                'name' => "MVP - Jalapeno Popper",
                'slug' => "mvp-jalapeno-popper",
                'tags' => ['jalapeno', 'cheddar', 'jalapeno-cream-cheese-sauce'],
                'description' => "Limited Edition Cream cheese sauce, mozzarella & asiago cheeses, bacon, jalapeno peppers & garlic. Contains a bioengineered food ingredient. Your official game day pizza. Highest quality. Most valuable pizza. Proudly Wisconsin cheese. U.S. Inspected and passed by Department of Agriculture. www.bernatellos.com. To The Customer: Questions or comments? Retain label and plastic wrap, write to: Bernatello's Pizza Inc., Customer Service PO Box 740 Kaukauwa, WI 54130. Visit our website: www.bernatellos.com.",
                'image_url' => 'https://images.albertsons-media.com/is/image/ABS/970777781-ECOM?$ng-ecom-pdp-desktop$&defaultImage=Not_Available',
                'ingredients' => "Crust (Enriched Flour (Bleached Wheat Flour, Niacin, Reduced Iron, Thiamin Mononitrate, Riboflavin, Enzyme, Folic Acid], Water, Lard [Lard, BHA, Propyl Gallate with Citric Acid Added to Help Protect Flavor], Dough Conditioner [Malted Barley Flour, Dextrose), Salt, Sugar, Yeast [Yeast, Sorbitan Monostearate, Ascorbic Acid]), Jalapeno Cream Cheese Sauce (Water, [Cream Cheese (Pasteurized Milk and Cream, Cheese Culture, Salt, Carob Bean Gum), Sour Cream Powder (Cream, Cultures and Lactic Acid), Modified Food Starch, Whey, Nonfat Milk, Sugar, Less than 2% of Spices, Salt, Sodium Phosphate, Citric Acid, and Fully Refined Soybean Oil]), Low Moisture Part Skim Mozzarella Cheese (Pasteurized Part Skim Milk, Salt, Cheese Cultures, Enzymes), Fully Cooked Bacon Topping (Pork Cured with Water, Salt, Sodium Phosphate, Sodium Erythorbate, Sodium Nitrite, May Also Contain Sugar, Flavoring, Smoke Flavor, Brown Sugar), Jalapeno Pepper, Shredded Asiago Cheese (Asiago Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes] Powdered Cellulose [to Prevent Caking]), Minced Garlic.",
                'allergens' => "Wheat, Milk, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => 4,
                    'serving_fraction' => '1/4',
                    'serving_weight' => 0,
                    'calories' => 400,
                    'caloris_from_fat' => 0,
                    'total_fat' => 21,
                    'saturated_fat' => 11,
                    'trans_fat' => 0.5,
                    'cholesterol' => 60,
                    'sodium' => 900,
                    'total_carbohydrate' => 34,
                    'dietary_fiber' => 1,
                    'total_sugars' => 4,
                    'added_sugars' => 1,
                    'protein' => 15,
                    'vitamin_d' => 0.4,
                    'calcium' => 320,
                    'iron' => 2,
                    'potassium' => 290,
                ]
            ],
        ];

        foreach ($pizzas as $pizza) {
            PizzaSeedHandler::seedPizza($brand, $pizza);
        }
    }
}
