<?php

namespace Database\Seeders;

use App\Handlers\ImageHandler;
use App\Models\Brand;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Handlers\PizzaSeedHandler;

use function PHPSTORM_META\map;

class HeggiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $brand = Brand::updateOrCreate([
            'slug' => 'heggies',
        ], [
            'name' => 'Heggies',
            'website' => 'https://www.heggiespizza.com/',
            'description' => 'Heggies Pizza is a premium frozen pizza brand that crafts handmade thin crust pizzas using the freshest and best ingredients. Based in Milaca, Minnesota, we\'ve been making handmade thin crust pizzas for over 28 years.',
            'brand_story' => 'Our founders set up shop in a small town in northern Minnesota, making thin crust pizzas by hand and freezing them for local resort owners – and a tradition was born. Though we are a bit bigger today, we are still driven by the same values: stay humble, stay authentic, and take care of our customers.',
            'founded_year' => '1989', // Approximately based on "28 years in" from website content
            'seo_title' => 'Heggies Pizza - Premium Frozen Pizza Made in Minnesota',
            'seo_description' => 'Heggies Pizza crafts premium frozen pizzas using the freshest and best ingredients. Based in Milaca, Minnesota, we\'ve been making handmade thin crust pizzas for over 28 years.',
            'seo_about_content' => '28 years in, our pizzas are still handmade with the freshest and best ingredients we can find. It\'s nothing fancy – just great pizza. People love the taste so much, they\'ve been known to chase down our delivery trucks to find out where they can get them!',
            'unique_selling_points' => 'Handmade thin crust pizzas, Premium fresh ingredients, Made in Minnesota, Strong community involvement',
            'social_media_handles' => json_encode([
                'facebook' => 'HeggiesPizza',
                'twitter' => 'HeggiesPizza',
                'instagram' => 'heggiespizza'
            ])
        ]);

        if (!$brand->image) {
            $image = ImageHandler::createFromUrl(
                'https://isd196nordicski.org/wp-content/uploads/sites/2860/2024/10/Screenshot-2024-10-29-at-10.25.06%E2%80%AFAM.png',
                'public',
                'images/logos/frozen/Heggies.png',
                'heggies'
            );
            $brand->image_id = $image->id;
            $brand->save();
        }

        $pizzas = [
            [
                'name' => "Cauliflower Crust Chicken Alfredo",
                'slug' => 'cauliflower-crust-chicken-alfredo',
                'description' => "Cauliflower crust pizza topped with white chicken, alfredo sauce and mozzarella cheese",
                'tags' => ['cauliflower-crust', 'chicken', 'alfredo', 'thin-crust'],
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '4 servings per container',
                    'serving_size' => '1/4 pizza (141 g)',
                    'calories' => 340,
                    'total_fat' => '15g',
                    'saturated_fat' => '9g',
                    'trans_fat' => '0.5g',
                    'cholesterol' => '70mg',
                    'sodium' => '970mg',
                    'total_carbohydrate' => '30g',
                    'dietary_fiber' => '0g',
                    'total_sugars' => '4g',
                    'added_sugars' => '1g',
                    'protein' => '20g',
                    'vitamin_d' => '0.1mcg',
                    'potassium' => '210mg',
                    'iron' => '0.7mg',
                    'calcium' => '380mg',
                ]

            ],
            [
                'name' => "Cauliflower Sausage & Pepperoni",
                'slug' => "cauliflower-sausage-pepperoni",
                'description' => "Cauliflower crust pizza topped with sausage, pepperoni, and mozzarella cheese",
                'tags' => ['cauliflower-crust', 'meat', 'sausage', 'pepperoni', 'thin-crust'],
                'allergens' => "Milk, Wheat, Soy",
                'ingredients' => "CAULIFLOWER CRUST (CAULIFLOWER, LOW MOISTURE MOZZARELLA CHEESE [PASTEURIZED MILK, CHEESE CULTURES, SALT, ENZYME], TAPIOCA STARCH, RICE FLOUR, RICE STARCH, EGG WHITES, MODIFIED RICE STARCH, CONTAINS LESS THAN 2% OF THE FOLLOWING: CANE SUGAR, YEAST, SALT, GARLIC POWDER, SPICES, XANTHAN GUM, CULTURED BROWN RICE, BROWN RICE FLOUR, CITRIC ACID, LACTIC ACID), LOW-MOISTURE PART-SKIM MOZZARELLA CHEESE (PASTEURIZED PART-SKIM MILK, CHEESE CULTURE, SALT, ENZYMES), SAUCE (TOMATO PASTE [TOMATOES, CITRIC ACID], WATER, SALT, SPICES, GARLIC, ONION), SAUSAGE (BEEF, PORK, WATER, SALT WITH ANTIOXIDANT BLEND [SALT, ROSEMARY EXTRACT, BHA {.041%}, BHT {.041%}, CITRIC ACID {.041%}, LESS THAN 2% TRICALCIUM PHOSPHATE ADDED TO PREVENT CAKING], SEASONING [MONOSODIUM GLUTAMATE, SPICES, DEHYDRATED GARLIC]), PEPPERONI (PORK, BEEF, SALT, SPICES, DEXTROSE, LACTIC ACID STARTER CULTURE, OLEORESIN OF PAPRIKA, FLAVORINGS, SODIUM ASCORBATE, SODIUM NITRITE, BHA, BHT, CITRIC ACID. MAY CONTAIN 2% OR LESS OF WATER, GARLIC POWDER).",
                'nutritional_facts' => [
                    'serving_per_container' => '5 servings per container',
                    'serving_size' => '1/5 pizza (126g)',
                    'calories' => 340,
                    'total_fat' => '20g',
                    'saturated_fat' => '10g',
                    'trans_fat' => '0.5g',
                    'cholesterol' => '60mg',
                    'sodium' => '990mg',
                    'total_carbohydrate' => '23g',
                    'dietary_fiber' => '1g',
                    'total_sugars' => '4g',
                    'added_sugars' => '1g',
                    'protein' => '18g',
                    'calcium' => '350mg',
                    'iron' => '0.9mg',
                    'potassium' => '270mg',
                    'vitamin_d' => '0mcg',
                ]
            ],
            [
                'name' => "Italian Beef Pizza",
                'slug' => "italian-beef-pizza",
                'description' => "Sliced beef, Giardiniera, sweety drop peppers and a blend of mozzarella and provolone cheeses",
                'tags' => ['beef','thin-crust'],
                'image_url' => "https://www.kroger.com/product/images/large/front/0088570901222",
                'ingredients' => "",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '5 servings per container',
                    'serving_size' => '1/5 pizza (141g)',
                    'calories' => 320,
                    'total_fat' => '13g',
                    'saturated_fat' => '6g',
                    'trans_fat' => '0g',
                    'cholesterol' => '35mg',
                    'sodium' => '680mg',
                    'total_carbohydrate' => '32g',
                    'dietary_fiber' => '2g',
                    'total_sugars' => '4g',
                    'added_sugars' => '<1g',
                    'protein' => '18g',
                    'vitamin_d' => '0.2mcg',
                    'potassium' => '280mg',
                    'iron' => '1.2mg',
                    'calcium' => '310mg',
                ]
            ],
            [
                'name' => "Cauliflower Crust Margherita",
                'slug' => "cauliflower-crust-margherita",
                'description' => "Cauliflower crust pizza topped with tomato, basil, garlic and sliced mozzarella cheese",
                'tags' => ['vegetarian', 'cauliflower-crust', 'thin-crust'],
                'image_url' => "https://www.kroger.com/product/images/xlarge/front/0088570901217",
                'ingredients' => "CAULIFLOWER CRUST (CAULIFLOWER, LOW MOISTURE MOZZARELLA CHEESE [PASTEURIZED MILK, CHEESE CULTURES, SALT, ENZYME], TAPIOCA STARCH, RICE FLOUR, RICE STARCH, EGG WHITES, MODIFIED RICE STARCH, CONTAINS LESS THAN 2% OF THE FOLLOWING: CANE SUGAR, YEAST, SALT, GARLIC POWDER, SPICES, XANTHAN GUM, CULTURED BROWN RICE, BROWN RICE FLOUR, CITRIC ACID, LACTIC ACID), SAUCE (TOMATO PASTE [TOMATOES, CITRIC ACID], WATER, SALT, SPICES, GARLIC, ONION), LOW-MOISTURE PART-SKIM MOZZARELLA CHEESE (PASTEURIZED PARTSKIM MILK, CHEESE CULTURE, SALT, ENZYMES), FRESH MOZZARELLA CHEESE (PASTEURIZED MILK, VINEGAR, ENZYMES, SALT), TOMATOES, BASIL, DEHYDRATED GARLIC.",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '4 servings per container',
                    'serving_size' => '1/4 pizza (125g)',
                    'calories' => 290,
                    'total_fat' => '12g',
                    'saturated_fat' => '7g',
                    'trans_fat' => '0g',
                    'cholesterol' => '40mg',
                    'sodium' => '600mg',
                    'total_carbohydrate' => '30g',
                    'dietary_fiber' => '2g',
                    'total_sugars' => '4g',
                    'added_sugars' => '1g',
                    'protein' => '15g',
                    'vitamin_d' => '0mcg',
                    'potassium' => '280mg',
                    'iron' => '1mg',
                    'calcium' => '340mg',
                ]
            ],
            [
                'name' => "Double Cheese Pizza",
                'slug' => "double-cheese-pizza",
                'description' => "The ultimate cheese-lover's pizza, topped with cheddar and mozzarella",
                'tags' => ['vegetarian', 'cheese-lovers', 'thin-crust'],
                'image_url' => "https://target.scene7.com/is/image/Target/GUEST_9b59602e-3f25-4177-9a33-42c808415631?wid=800&hei=800&qlt=80&fmt=webp",
                'ingredients' => "crust: (flour [wheat, malted barley], water, soybean oil, yeast, salt, dextrose, calcium propionate [preservative], soy lecithin), mozzarella cheese (pasteurized partially skimmed milk, cheese cultures, salt, enzymes), sauce (water, tomato paste [tomatoes, citric acid], salt, spices, garlic, onion, natural flavor), cheddar cheese (pasteurized cultured milk, salt, enzymes, annatto [color]).",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '4 servings per container',
                    'serving_size' => '1/4 pizza (142g)',
                    'calories' => 340,
                    'total_fat' => '15g',
                    'saturated_fat' => '8g',
                    'trans_fat' => '0g',
                    'cholesterol' => '40mg',
                    'sodium' => '670mg',
                    'total_carbohydrate' => '32g',
                    'dietary_fiber' => '1g',
                    'total_sugars' => '3g',
                    'added_sugars' => '0g',
                    'protein' => '19g',
                    'vitamin_d' => '0mcg',
                    'potassium' => '260mg',
                    'iron' => '1mg',
                    'calcium' => '460mg',
                ]
            ],
            [
                'name' => "Sausage",
                'slug' => "sausage",
                'description' => "Made with sausage and mozzarella cheese",
                'tags' => ['sausage', 'thin-crust'],
                'image_url' => "https://tb-static.uber.com/prod/image-proc/processed_images/e5fcb13618f558c059420dcd523ba6d6/957777de4e8d7439bef56daddbfae227.jpeg",
                'allergens' => "Milk, Wheat, Soy",
                'ingredients' => "Ingredients: Mozzarella Cheese (Pasteurized Partially Skimmed Milk, Cheese Cultures, Salt, Enzymes), Crust: (Flour [Wheat, Malted Barley], Water, Soybean Oil, Yeast, Salt, Dextrose, Calcium Propionate [Preservative], Soy Lecithin), Sauce (Water, Tomato Paste [Tomatoes, Citric Acid], Salt, Spices, Garlic, Onion, Natural Flavor), Sausage (Beef, Pork, Water, Salt with Antioxidant Blend [Salt, Rosemary Extract, BHA (0.041%), BHT (0.041%), Citric Acid (0.041%), Less than 2% Tricalcium Phosphate Added to Prevent Caking], Spices [Monosodium Glutamate, Spices, Dehydrated Garlic]).",
                'nutritional_facts' => [
                    'serving_per_container' => '5 servings per container',
                    'serving_size' => '1/5 pizza (136g)',
                    'calories' => 310,
                    'total_fat' => '14g',
                    'saturated_fat' => '7g',
                    'trans_fat' => '0g',
                    'cholesterol' => '45mg',
                    'sodium' => '690mg',
                    'total_carbohydrate' => '27g',
                    'dietary_fiber' => '1g',
                    'total_sugars' => '2g',
                    'added_sugars' => '0g',
                    'protein' => '20g',
                    'vitamin_d' => '0mcg',
                    'potassium' => '260mg',
                    'iron' => '1.1mg',
                    'calcium' => '410mg',
                ]
            ],
            [
                'name' => "Pepperoni",
                'slug' => "pepperoni",
                'description' => "Covered from edge to edge with pepperoni and mozzarella cheese",
                'tags' => ['pepperoni', 'thin-crust'],
                'ingredients' => "thin crust: flour (wheat, malted barley), water, soybean oil, yeast, salt, dextrose, calcium propionate and soy lecithin. cheese: mozzarella cheese (cultured pasteurized partially skimmed milk, salt and enzymes). meat topping: pepperoni: pork and beef, salt, contains 2% or less of water, dextrose, spices, oleoresin of paprika, lactic acid starter culture, garlic powder, sodium nitrite, bha, bht, citric acid. sauce: tomato paste, water, salt, spices, flavoring, dehydrated garlic, citric acid.",
                'image_url' => "https://target.scene7.com/is/image/Target/GUEST_685f4939-4c38-4fb8-b197-31c8c28fdc02?wid=800&hei=800&qlt=80&fmt=webp",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '5 servings per container',
                    'serving_size' => '1/5 pizza (130g)',
                    'calories' => 350,
                    'total_fat' => '19g',
                    'saturated_fat' => '9g',
                    'trans_fat' => '0g',
                    'cholesterol' => '50mg',
                    'sodium' => '850mg',
                    'total_carbohydrate' => '26g',
                    'dietary_fiber' => '1g',
                    'total_sugars' => '2g',
                    'added_sugars' => '0g',
                    'protein' => '18g',
                    'vitamin_d' => '0mcg',
                    'potassium' => '240mg',
                    'iron' => '1.1mg',
                    'calcium' => '340mg',
                ]
            ],
            [
                'name' => "Sausage and Pepperoni",
                'slug' => "sausage-and-pepperoni",
                'description' => "Featuring sausage, pepperoni and mozzarella cheese",
                'tags' => ['sausage', 'pepperoni', 'thin-crust'],
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '5 servings per container',
                    'serving_size' => '1/5 pizza (147g)',
                    'calories' => 370,
                    'total_fat' => '19g',
                    'saturated_fat' => '9g',
                    'trans_fat' => '0.5g',
                    'cholesterol' => '55mg',
                    'sodium' => '1050mg',
                    'total_carbohydrate' => '26g',
                    'dietary_fiber' => '1g',
                    'total_sugars' => '2g',
                    'added_sugars' => '0g',
                    'protein' => '22g',
                    'vitamin_d' => '0.4mcg',
                    'potassium' => '300mg',
                    'iron' => '1.4mg',
                    'calcium' => '400mg',
                ]
            ],
            [
                'name' => "Sausage and Mushroom",
                'slug' => "sausage-and-mushroom",
                'description' => "Loaded up with sausage, mushrooms and mozzarella cheese",
                'tags' => ['thin-crust', 'sausage', 'mushroom'],
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '6 servings per container',
                    'serving_size' => '1/6 pizza (132g)',
                    'calories' => 250,
                    'total_fat' => '11g',
                    'saturated_fat' => '5g',
                    'trans_fat' => '0g',
                    'cholesterol' => '35mg',
                    'sodium' => '780mg',
                    'total_carbohydrate' => '23g',
                    'dietary_fiber' => '2g',
                    'total_sugars' => '3g',
                    'added_sugars' => '0g',
                    'protein' => '16g',
                    'vitamin_d' => '0mcg',
                    'potassium' => '240mg',
                    'iron' => '1.1mg',
                    'calcium' => '320mg',
                ]
            ],
            [
                'name' => "Deluxe Combo",
                'slug' => "deluxe-combo",
                'description' => "Made with sausage, pepperoni, onions, mushrooms and the freshest sliced-and-diced green peppers. Topped with plenty of mozzarella cheese",
                'tags' => ['supreme', 'sausage', 'pepperoni', 'mushroom', 'thin-crust'],
                'image_url' => "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_1cf9f542-c6eb-4d14-bec1-e134f2904e7f.jpg",
                'ingredients' => "Meat Topping (sausage [beef, Pork, Water, Salt With Antioxidant Blend {salt, Rosemary Extract, Bha (0.041%), Bht (0.041%), Citric Acid (0.041%), Less Than 2% Tricalcium Phosphate Added To Prevent Caking}, Spices {monosodium Glutamante, Spices, Dehydrated Garlic}], Pepperoni [pork, Beef, Salt, Contains 2% Or Less Of: Water, Dextrose, Spices, Flavoring, Lactic Acid Starter Culture, Sodium Ascorbate, Oleoresin Of Paprika, Garlic Powder, Sodium Nitrite, Bha, Bht, Citric Acid]), Mozzarella (cultured Pasteurized Partially Skimmed Milk, Salt, Enzymes), Crust (flour [wheat, Malted Barley], Water, Soybean Oil, Yeast, Salt, Dextrose, Calcium Propionate [preservative], Soy Lecithin), Sauce (tomato Paste, Water, Salt, Garlic, Spices, Natural Flavor, Onion, Citric Acid), Mushrooms (mushrooms, Water, Salt, Citric Acid, Ascorbic Acid, Calcium Disodium Edta [to Retain Color]), Onion, Bell Pepper.",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '6 servings per container',
                    'serving_size' => '1/6 pizza (151g)',
                    'calories' => 310,
                    'total_fat' => '16g',
                    'saturated_fat' => '7g',
                    'trans_fat' => '0g',
                    'cholesterol' => '45mg',
                    'sodium' => '960mg',
                    'total_carbohydrate' => '24g',
                    'dietary_fiber' => '2g',
                    'total_sugars' => '3g',
                    'added_sugars' => '0g',
                    'protein' => '18g',
                    'vitamin_d' => '0.4mcg',
                    'potassium' => '290mg',
                    'iron' => '1.4mg',
                    'calcium' => '320mg',
                ]
            ],
            [
                'name' => "Six Pack®",
                'slug' => "six-pack",
                'description' => "Made with 4 meats and 2 cheeses. Loaded with sausage, pepperoni, Canadian bacon, bacon, cheddar and mozzarella",
                'tags' => ['meat-lovers', 'sausage', 'bacon', 'pepperoni', 'canadian-bacon', 'cheese-lovers', 'thin-crust'],
                'image_url' => "https://www.kroger.com/product/images/xlarge/front/0088570901230",
                'allergens' => "Milk, Wheat, Soy",
                'ingredients' => "CRUST (FLOUR [WHEAT, MALTED BARLEY], WATER, SOYBEAN OIL, YEAST, SALT, DEXTROSE, CALCIUM PROPIONATE [PRESERVATIVE], SOY LECITHIN), LOW-MOISTURE PART-SKIM MOZZARELLA CHEESE (PASTEURIZED PART-SKIM MILK, CHEESE CULTURE, SALT, ENZYMES), SAUCE (TOMATO PASTE [TOMATOES, CITRIC ACID] , WATER, SALT, SPICES, GARLIC, ONION), CANADIAN STYLE BACON MADE FROM PORK SIRLOIN HIPS, CHOPPED AND FORMED, (PORK, WATER, SALT, SUGAR, SODIUM PHOSPHATE, SEASONING [SODIUM ACETATE, SALT, SODIUM DIACETATE], FLAVORING, SMOKE FLAVORING, SODIUM ERYTHORBATE, SODIUM NITRITE), SAUSAGE (BEEF, PORK, WATER, SALT WITH ANTIOXIDANT BLEND [SALT, ROSEMARY EXTRACT, BHA {0.041%}, BHT {0.041%}, CITRIC ACID {0.041%}, LESS THAN 2% TRICALIUM PHOSPHATE ADDED TO PREVENT CAKING], SEASONING (MONOSODIUM GLUTAMATE, SPICES, DEHYDRATED GARLIC), PEPPERONI (PORK, BEEF, SALT, SPICES, DEXTROSE, LACTIC ACID STARTER CULTURE, OLEORESIN OF PAPRIKA, FLAVORINGS, SODIUM ASCORBATE, SODIUM NITRITE, BHA, BHT, CITRIC ACID, MAY CONTAIN 2% OR LESS OF WATER, GARLIC POWDER), BACON (PORK CURED WITH WATER, SALT, SODIUM ERYTHORBATE, SODIUM NITRITE, MAY CONTAIN LESS THAN 2% OF SUGAR, BROWN SUGAR, POTASSIUM CHLORIDE, SODIUM PHOSPHATES, FLAVORINGS, NATURAL SMOKE FLAVORING, MAPLE FLAVORING AND SEASONING, [CORN SYRUP, NATURAL & ARTIFICIAL FLAVOR, CARAMEL COLOR, SUGAR, MAPLE SUGAR, GLUCOSE SYRUP SOLIDS, ORGANIC INVERT SUGAR SYRUP, LACTIC ACID, MAPLE SYRUP], SODIUM DIACETATE, DEXTROSE), CHEDDAR CHEESE (PASTEURIZED CULTURED MILK, SALT, ENZYMES, ANNATTO [COLOR]).",
                'nutritional_facts' => [
                    'serving_per_container' => '6 servings per container',
                    'serving_size' => '1/6 pizza (142g)',
                    'calories' => 380,
                    'total_fat' => '21g',
                    'saturated_fat' => '9g',
                    'trans_fat' => '0g',
                    'cholesterol' => '70mg',
                    'sodium' => '1320mg',
                    'total_carbohydrate' => '22g',
                    'dietary_fiber' => '1g',
                    'total_sugars' => '2g',
                    'added_sugars' => '0g',
                    'protein' => '25g',
                    'vitamin_d' => '0.5mcg',
                    'potassium' => '390mg',
                    'iron' => '1.5mg',
                    'calcium' => '320mg',
                ]
            ],
            [
                'name' => "Chicken Alfredo",
                'slug' => "chicken-alfredo",
                'description' => "Made with garlic chicken, creamy alfredo sauce and mozzarella cheese on a thick, seasoned, hand-stretched crust",
                'tags' => ['chicken', 'alfredo', 'thin-crust'],
                'image_url' => "https://images.freshop.ncrcloud.com/00885709012291/763f6d7ff481fdca1770558728ddeb9b_large.png",
                'allergens' => "Milk, Wheat, Soy",
                'ingredients' => "Crust: (Flour [Wheat, Malted Barley], Water, Soybean Oil, Yeast, Salt, Dextrose, Leavening [Sodium Aluminum Phosphate, Sodium Bicarbonate], Calcium Propionate [Preservative], Soy Lecithin), Mozzarella Cheese (Pasteurized Partially Skimmed Milk, Cheese Cultures, Salt, Enzymes), Alfredo Sauce (Skim Milk, Water, Cream, Cream Cheese [Pasteurized Milk and Cream, Cheese Cultures, Salt, Guar Gum, Carob Bean Gum, Xanthan Gum], Parmesan Cheese [Cultured Milk, Salt, Enzymes], Romano Cheese [Pasteurized Cow's Milk, Cheese Culture, Salt, Enzymes], Butter [Cream, Salt], Food Starch - Modified, Contains Less than 2% of Maltodextrin, Salt, Natural Flavors, Sodium Phosphate, Sodium Citrate, Cellulose Gel, Cellulose Gum, Mono and Diglycerides, Spice), White Meat Chicken Strips (White Meat Chicken, Water, Salt, Contains 2% or Less of: Dextrose, Garlic Powder, Modified Food Starch, Dehydrated Onion, Sodium Phosphates, Tapioca Dextrin, Spices [Including Celery Seed], Dehydrated Garlic, Grill Flavor [from Sunflower Oil]), Italian Seasoning (Oregano, Marjoram, Thyme, Basil, Rosemary, Sage), Parsley.",
                'nutritional_facts' => [
                    'serving_per_container' => '5 servings per container',
                    'serving_size' => '1/5 pizza (130g)',
                    'calories' => 300,
                    'total_fat' => '13g',
                    'saturated_fat' => '6g',
                    'trans_fat' => '0g',
                    'cholesterol' => '45mg',
                    'sodium' => '760mg',
                    'total_carbohydrate' => '30g',
                    'dietary_fiber' => '1g',
                    'total_sugars' => '2g',
                    'added_sugars' => '0g',
                    'protein' => '17g',
                    'vitamin_d' => '0mcg',
                    'potassium' => '230mg',
                    'iron' => '0.7mg',
                    'calcium' => '300mg',
                ]
            ],
            [
                'name' => "Breakfast",
                'slug' => "breakfast",
                'description' => "Made with country sausage, bacon, scrambled eggs, green onions, cheddar, mozzarella and country gravy",
                'tags' => ['breakfast', 'sausage', 'bacon', 'thin-crust'],
                'image_url' => "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_2c66227f-c4d0-4b3c-9772-c650a586bde3.jpg",
                'allergens' => "Milk, Wheat, Soy, Egg",
                'ingredients' => "Crust: (Flour [Wheat, Malted Barley], Water, Soybean Oil, Yeast, Salt, Dextrose, Calcium Propionate [Preservative], Soy Lecithin), White Cream Sauce (Water, Cream [Milk, Vegetable Oil [Corn, Canola, and/or Soybean], Wheat Flour, Modified Food Starch, Contains Less than 2% of: Salt, Soy Protein Concentrate, Yeast Extract, Flavoring, Onion Extract), Mozzarella Cheese (Pasteurized Partially Skimmed Milk, Cheese Cultures, Salt, Enzymes), Cooked Scrambled Eggs (Whole Eggs, Skim Milk, Soybean Oil, Modified Corn Starch, Salt, Xanthan Gum, Liquid Pepper Extract, Citric Acid, Natural and Artificial Butter Flavor (Butter [Cream], Lipolyzed Butter Oil, Medium Chain Triglycerides, Natural and Artificial Flavors, Soybean Oil, Annatto Extract]), Cooked Country Style Sausage (Pork, Water, Salt, Sugar, Spices, Sodium Phosphate, Autolyzed Yeast, Flavorings), Cheddar Cheese (Pasteurized Cultured Milk, Salt, Enzymes, Annatto [Color]), Bacon (Pork Cured with Water, Salt, Sugar, Sodium Erythorbate and/or Sodium Ascorbate, Sodium Nitrite, Natural Smoke Flavor, Sodium Phosphate), Green Onion, Black Pepper.",
                'nutritional_facts' => [
                    'serving_per_container' => '6 servings per container',
                    'serving_size' => '1/6 pizza (127g)',
                    'calories' => 360,
                    'total_fat' => '21g',
                    'saturated_fat' => '7g',
                    'trans_fat' => '0g',
                    'cholesterol' => '95mg',
                    'sodium' => '770mg',
                    'total_carbohydrate' => '26g',
                    'dietary_fiber' => '1g',
                    'total_sugars' => '2g',
                    'added_sugars' => '0g',
                    'protein' => '17g',
                    'vitamin_d' => '0.4mcg',
                    'potassium' => '160mg',
                    'iron' => '0.5mg',
                    'calcium' => '250mg',
                ]
            ],
            [
                'name' => "BCB® Bacon Cheeseburger",
                'slug' => "bcb-bacon-cheeseburger",
                'description' => "A hearty pizza made with bacon, beef, cheddar and mozzarella",
                'tags' => ['bacon', 'cheeseburger', 'thin-crust'],
                'image_url' => "https://images.cdn.cub.com/detail/25f680c9-f08c-4b95-b0a0-e9a4cc8aa0e5.jpeg",
                'allergens' => "Milk, Wheat, Soy",
                'ingredients' => "Thin Crust: Flour (Wheat, Malted Barley), Water, Soybean Oil, Yeast, Salt, Dextrose, Calcium Propionate, and Soy Lecithin. Cheese: Mozzarella Cheese (Cultured Pasteurized Partially Skimmed Milk, Salt and Enzymes). Meat Topping: Cooked Beef Topping: Beef, Water, Salt, Sodium Phosphate, Spice, Sugar, BHA, BHT, Citric Acid. Precooked Bacon Topping: Cured with Water, Salt, Sugar, Sodium Erythorbate and/or Sodium Ascorbate, Sodium Nitrite, May Contain Natural Smoke Flavoring, Sodium Phosphate. Sauce: Tomato Paste, Water, Salt, Spices, Flavoring, Dehydrated Garlic, Onion, Citric Acid, Cheese: Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes and Annatto [Vegetable Color]).",
                'nutritional_facts' => [
                    'serving_per_container' => '6 servings per container',
                    'serving_size' => '1/6 pizza (132g)',
                    'calories' => 380,
                    'total_fat' => '22g',
                    'saturated_fat' => '11g',
                    'trans_fat' => '0.5g',
                    'cholesterol' => '55mg',
                    'sodium' => '1000mg',
                    'total_carbohydrate' => '21g',
                    'dietary_fiber' => '1g',
                    'total_sugars' => '4g',
                    'added_sugars' => '0g',
                    'protein' => '23g',
                    'vitamin_d' => '0mcg',
                    'potassium' => '260mg',
                    'iron' => '1.2mg',
                    'calcium' => '360mg',
                ]
            ],
            [
                'name' => "El Jefe®",
                'slug' => "el-jefe",
                'description' => "The boss of Mexican pizzas. Mozzarella and cheddar cheese, Mexican-spiced tomato sauce, chorizo, diced jalapenos, black olives, and green onions",
                'tags' => ['mexican', 'spicy', 'chorizo', 'jalapeno', 'thin-crust'],
                'image_url' => "https://www.instacart.com/image-server/699x699/filters:fill(FFF,true):format(webp)/www.instacart.com/assets/domains/product-image/file/large_6ae35f28-77b1-4c79-b451-eccbdf8e2160.jpg",
                'ingredients' => "Cheese: Mozzarella Cheese (Cultured Pasteurized Partially Skimmed Milk, Salt and Enzymes), Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes and Annatto [Vegetable Color]), Crust: Flour (Wheat Flour, Barley Flour), Water, Soybean Oil, Yeast, Salt, Dextrose, Calcium Propionate (Preservative) and Soy Lecithin, Sauce: Tomato Paste, Water, Seasoning (Yellow Corn Flour, Salt, Maltodextrin, Paprika, Spices, Modified Corn Starch, Sugar, Garlic Powder, Citric Acid, Yeast Extract, Natural Flavor, Silicon Dioxide), Kosher Salt, Sugar, Liquid Smoke, Meat Topping: Fully Cooked Pork, Water, Spices, Paprika, Salt, Sugar, Flavorings, Citric Acid, Sodium Phosphates, Turmeric, Diced Jalapenos: Jalapeno Peppers, Water, Citric Acid, Salt, Calcium Chloride, Black Olives: Ripe Olives, Water, Salt and Ferrous Gluconate (Added to Stabilize Color), Green Onions.",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '5 servings per container',
                    'serving_size' => '1/5 pizza (147g)',
                    'calories' => 350,
                    'total_fat' => '17g',
                    'saturated_fat' => '8g',
                    'trans_fat' => '0g',
                    'cholesterol' => '45mg',
                    'sodium' => '860mg',
                    'total_carbohydrate' => '30g',
                    'dietary_fiber' => '2g',
                    'total_sugars' => '4g',
                    'added_sugars' => '1g',
                    'protein' => '18g',
                    'vitamin_d' => '0mcg',
                    'potassium' => '300mg',
                    'iron' => '1.2mg',
                    'calcium' => '380mg',
                ]
            ],
            [
                'name' => "Inferno",
                'slug' => "inferno",
                'description' => "Voted #1 best frozen pizza by the Star Tribune",
                'tags' => ['spicy', 'jalapeno', 'sausage', 'pepperoni', 'thin-crust'],
                'image_url' => "https://target.scene7.com/is/image/Target/GUEST_d0db2cf8-add3-474a-9989-9056247d2027?wid=800&hei=800&qlt=80&fmt=webp",
                'ingredients' => "cheese: mozzarella cheese (cultured pasteurized partially skimmed milk, salt and enzymes). thin crust: flour (wheat, malted barley). water, soybean oil, yeast, salt, dextrose, calcium propionate, and soy lecithin, meat topping: sausage: beef and pork, water, salt, spices, monosodium glutamate, dehydrated garlic. pepperoni: pork and beef, salt, contains 2% or less of water, dextrose, spices, oleoresin of paprika, lactic acid starter culture, garlic powder, sodium nitrite, bha, bht, citric acid. sauce: tomato paste, water, salt, spices, flavoring, dehydrated garlic, citric acid. vegetable topping: jalapeno peppers, water, distilled vinegar, salt, calcium chloride.",
                'allergens' => "Milk, Wheat, Soy",
                'nutritional_facts' => [
                    'serving_per_container' => '6 servings per container',
                    'serving_size' => '1/6 pizza (132g)',
                    'calories' => 340,
                    'total_fat' => '19g',
                    'saturated_fat' => '8g',
                    'trans_fat' => '0g',
                    'cholesterol' => '50mg',
                    'sodium' => '1210mg',
                    'total_carbohydrate' => '24g',
                    'dietary_fiber' => '1g',
                    'total_sugars' => '3g',
                    'added_sugars' => '0g',
                    'protein' => '17g',
                    'vitamin_d' => '1mcg',
                    'calcium' => '300mg',
                    'iron' => '1.5mg',
                    'potassium' => '340mg',
                ]
                
            ]
        ];

        foreach ($pizzas as $pizza) {
            PizzaSeedHandler::seedPizza($brand, $pizza);
        }
    }
}
